# https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/
groups:
- name: watchdog
  rules:
  - alert: WatchDog
    expr: vector(1)
    labels:
      severity: info
    annotations:
      description: This is a watchdog alert meant to ensure that the entire alerting pipeline is functional.
      summary: Watchdog alert
